---
version: "3.7"
services:
  frontend-nginx:
    build:
      context: ./
      dockerfile: docker/frontend-nginx/Dockerfile
      args:
        FRONTEND_NGINX_PORT: ${FRONTEND_NGINX_PORT:-8080}
        BACKEND_CACHE_PORT: ${BACKEND_CACHE_PORT:80}
    ports:
      - 80:${FRONTEND_NGINX_PORT:-8080}
    volumes:
      - ./dist:/dist:ro
      - type: tmpfs
        target: /var/cache/nginx
      - type: tmpfs
        target: /var/run/nginx
    depends_on:
      - backend-cache
    networks:
      - frontend_web
  backend-cache:
    build:
      context: ./docker/backend-cache
      dockerfile: Dockerfile
    volumes:
      - type: tmpfs
        target: /var/lib/varnish:exec
      - type: tmpfs
        target: /usr/local/var/varnish:exec
    expose:
      - ${BACKEND_CACHE_PORT:-80}
    networks:
      - frontend_web
      - backend_app
    depends_on:
      - backend-nginx
  backend-nginx:
    build:
      context: ./
      dockerfile: docker/backend-nginx/Dockerfile
      args:
        APP_GROUP_NAME: ${APP_GROUP_NAME:-app}
        APP_GROUP_ID: ${APP_GROUP_ID:-2001}
        PHP_SOCKET_DIR: ${PHP_SOCKET_DIR:-/socket}
        PHP_SOCKET_FILE: ${PHP_SOCKET_FILE:-app.sock}
    volumes:
      - socket:${PHP_SOCKET_DIR:-/socket}
    networks:
      - backend_app
    expose:
      - ${BACKEND_NGINX_PORT:-8081}
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
      args:
        APP_GROUP_NAME: ${APP_GROUP_NAME:-app}
        APP_GROUP_ID: ${APP_GROUP_ID:-2001}
        PHP_SOCKET_DIR: ${PHP_SOCKET_DIR:-/socket}
        PHP_SOCKET_FILE: ${PHP_SOCKET_FILE:-app.sock}
    volumes:
      - ./app:/site/app:ro
      - socket:${PHP_SOCKET_DIR:-/socket}
volumes:
  socket:
networks:
  frontend_web:
  backend_app:
